// generated by stringer -type storageItemType; DO NOT EDIT

package fsextender

import "fmt"

const _storageItemType_name = "type_UNKNOWNtype_FStype_DISKtype_LVM_GROUPtype_LVM_PVtype_LVM_PV_ADDtype_LVM_PV_NEWtype_LVM_LVtype_PARTITIONtype_PARTITION_NEWtype_SKIPtype_LAST"

var _storageItemType_index = [...]uint8{0, 12, 19, 28, 42, 53, 68, 83, 94, 108, 126, 135, 144}

func (i storageItemType) String() string {
	if i < 0 || i >= storageItemType(len(_storageItemType_index)-1) {
		return fmt.Sprintf("storageItemType(%d)", i)
	}
	return _storageItemType_name[_storageItemType_index[i]:_storageItemType_index[i+1]]
}
